package com.laptrinhjavaweb.entity;
// default package
// Generated Aug 11, 2020 8:47:55 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "ajax3")
public class City implements java.io.Serializable {

	private Integer id;
	private State state;
	private String name;

	public City() {
	}

	public City(State state, String name) {
		this.state = state;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stateId")
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
